language: cpp
dist: bionic
compiler: gcc

before_install:
  - pip install --user cpp-coveralls

script: 
  - mkdir build && cd build;
  - cmake .. -DBUILD_COVERAGE=true;
  - cmake --build .;
  - ctest;
  - cd ..
  - gcov k3serializer.cpp --object-directory=./build/CMakeFiles/k3serializer.dir/;
  - gcov k3serializer.h --object-directory=./build/CMakeFiles/k3serializer.dir/;
after_success:
  - coveralls --exclude example --exclude test --exclude build --gcov-options '\-lp'